name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Frontend Artifact
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: ensure node is installed and right version
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: install deps
        run: cd frontend && npm i

      - name: compile/build
        run:  cd frontend && npm run build

      - name: upload the artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: frontend/build

  security-audit:
    name: check for vulnerabilities in my deps
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: ensure node is installed and right version
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: audit
        run: cd frontend && npm audit --omit=dev

  lint:
    name: 🧼 Ensure Code Style
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: fe-node-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install deps
        run: cd frontend && npm i

      - name: 😂 Lint code
        run: cd frontend && npm run lint
